version: "3.9"

services:
  api:
    image: ghcr.io/sgoridotla1/sur-accountant:latest
    container_name: api
    env_file:
      - .env
    volumes:
      - ./credentials:/app/credentials:ro
    ports:
      - "3000:3000" # change if needed
    restart: unless-stopped
